# Generated by Django 2.2.6 on 2019-11-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191104_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.BusinessProfile'),
        ),
    ]
