# Generated by Django 2.2.6 on 2019-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191106_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='company_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='recent_project',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='work_seeking',
            field=models.TextField(blank=True),
        ),
    ]
