# Generated by Django 2.2.6 on 2019-11-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191111_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='recent_project',
            new_name='recent_projects',
        ),
    ]
