# Generated by Django 2.2.7 on 2019-11-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191114_0704'),
        ('users', '0006_businessprofile_logo'),
    ]

    operations = [
    ]
