# Generated by Django 2.2.6 on 2019-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20191117_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='recent_projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='work_seeking',
            field=models.TextField(blank=True),
        ),
    ]
