# Generated by Django 2.2.7 on 2019-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191118_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
