# Generated by Django 2.2.7 on 2019-11-19 01:25

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191118_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='company_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='specialcredential',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='users.BusinessProfile'),
        ),
    ]
