# Generated by Django 2.2.7 on 2019-11-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20191117_2007'),
        ('users', '0009_auto_20191119_0543'),
        ('users', '0011_auto_20191119_0125'),
        ('users', '0010_auto_20191119_0045'),
    ]

    operations = [
    ]
