# Generated by Django 2.2.7 on 2019-11-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20191120_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='recent_projects',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='work_seeking',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
